train: False
cuda: True
ngpu: 1
gpu_id: '0'
data_dir: /data/datasets/yt8m/Train     # Your dataset path
video_flist: './filelists/Video_Name_List.txt'
audio_flist: './filelists/Audio_Name_List.txt'
workers: 4
batchSize: 40
manualSeed: False
checkpoint_folder: ./checkpoints
init_model: './checkpoints/VA_METRIC_DEMO_MODEL.pth'
topk: 5
log_dir: logs/
log_name: 'VA_METRIC_TEST'
