cuda: False
ngpu: 1
gpu_id: '0'
data_dir: /data/datasets/yt8m/Train         # replace it as your data path
flist: './filelists/train_filelist.txt'
workers: 4
batchSize: 64
manualSeed: 
adam: True
lr: 0.001
lr_decay: 0.7
lr_decay_epoch: 10
momentum: 0.9
weight_decay: 0.0001
max_epochs: 300
print_freq: 15
epoch_save: 10
checkpoint_folder: ./checkpoints
prefix: 'VA_METRIC'
model: ''
gradient_clip: 0.01
init_model: ''
